/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'siddharth' at '26/5/15 9:09 PM' with Gradle 2.3
 *
 * @author siddharth, @date 26/5/15 9:09 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
